// AUTO-GENERATED by body_export.py from raytrace.py CHOSEN geometry.
// config T_budget_ha_v2 dev=21.0 s2=-1.0 Lg=80.0 Lc=150.0 (built at Ha 656.28)
slitP   = [0.00, 0.00];
oap1P   = [50.80, 0.00];
gratP   = [-5.77, -56.57];
oap2P   = [55.24, 80.46];
sensP   = [-45.80, 69.84];
c0Ang   = 0.000;   // slit -> OAP1 chief
c1Ang   = -135.000;   // OAP1 -> grating (collimated)
c2Ang   = 66.000;   // grating -> OAP2 (diffracted)
dfAng   = -174.000;   // OAP2 -> sensor (focused)
gratNormAng = 108.721; // grating normal at Ha tuning
rfl1 = 50.8; rfl2 = 101.6;
// Ha incidence alpha=63.7 beta=42.7
gratNormAngs = [84.191, 108.721, 96.866];
// tuning detents: CaK=84.2, Ha=108.7, He1083=96.9
vaneX0 = 47.0;  // vane start: beam3 fan crosses by=25 at bx=30.5, fan r=10.6
