#!/usr/bin/env python3
"""Export the CHOSEN raytrace geometry as OpenSCAD constants (body_geom.scad).

Body coordinate convention (matches layout.png):
  bx = world z   (toward OAP1)
  by = world y   (fold/dispersion plane)
  bz = world x   (slit length / grating grooves) -> vertical, deck normal.

Run: .venv/bin/python body_export.py
"""

import math
from raytrace import Design, CONFIGS, CHOSEN, dot

cfg = CONFIGS[CHOSEN["config"]]
d = Design(lines_per_mm=2400.0, order=1, dev=CHOSEN["dev"], s2=CHOSEN["s2"],
           Lg=CHOSEN["Lg"], Lc=CHOSEN["Lc"], fold4=CHOSEN.get("fold4"), **cfg)
d.build(656.28)


def b(p):  # world (x,y,z) -> body (bx,by)
    return (p[2], p[1])


def bdir(v):
    n = math.hypot(v[2], v[1])
    return (v[2] / n, v[1] / n)


def ang(v):  # body-plane angle of a direction, degrees, atan2(by,bx)
    return math.degrees(math.atan2(v[1], v[2]))


lines = [
    "// AUTO-GENERATED by body_export.py from raytrace.py CHOSEN geometry.",
    f"// config {CHOSEN['config']} dev={CHOSEN['dev']} s2={CHOSEN['s2']} "
    f"Lg={CHOSEN['Lg']} Lc={CHOSEN['Lc']} (built at Ha 656.28)",
    f"slitP   = [{b(d.S)[0]:.2f}, {b(d.S)[1]:.2f}];",
    f"oap1P   = [{b(d.C1)[0]:.2f}, {b(d.C1)[1]:.2f}];",
    f"gratP   = [{b(d.G)[0]:.2f}, {b(d.G)[1]:.2f}];",
    f"oap2P   = [{b(d.C2)[0]:.2f}, {b(d.C2)[1]:.2f}];",
    f"sensP   = [{b(d.F2)[0]:.2f}, {b(d.F2)[1]:.2f}];",
    f"c0Ang   = {ang(d.c0):.3f};   // slit -> OAP1 chief",
    f"c1Ang   = {ang(d.c1):.3f};   // OAP1 -> grating (collimated)",
    f"c2Ang   = {ang(d.c2):.3f};   // grating -> OAP2 (diffracted)",
    f"df0Ang  = {ang(d.df0):.3f};   // OAP2 -> fold flat (focused)",
    f"dfAng   = {ang(d.df):.3f};   // final leg -> sensor",
    f"flat4P  = [{b(d.flat4[0])[0]:.2f}, {b(d.flat4[0])[1]:.2f}];"
    if d.flat4 else "flat4P = undef;",
    f"flat4NormAng = {ang(d.flat4[1]):.3f}; // seat face normal"
    if d.flat4 else "flat4NormAng = undef;",
    f"gratNormAng = {ang(d.gr.n):.3f}; // grating normal at Ha tuning",
    f"rfl1 = {cfg['rfl1']}; rfl2 = {cfg['rfl2']};",
]
alpha = math.degrees(math.acos(abs(dot(d.c1, d.gr.n))))
beta = math.degrees(math.acos(abs(dot(d.c2, d.gr.n))))
lines.append(f"// Ha incidence alpha={alpha:.1f} beta={beta:.1f}")

# per-line grating normal angles (tuning positions for the rotator detents)
tunings = []
for (label, lam, lpmm) in [("CaK", 393.37, 2400.0), ("Ha", 656.28, 2400.0),
                           ("He1083", 1083.0, 1200.0)]:
    dl = Design(lines_per_mm=lpmm, order=1, dev=CHOSEN["dev"],
                s2=CHOSEN["s2"], Lg=CHOSEN["Lg"], Lc=CHOSEN["Lc"],
                fold4=CHOSEN.get("fold4"), **cfg)
    dl.build(lam)
    tunings.append((label, ang(dl.gr.n)))
lines.append("gratNormAngs = [" +
             ", ".join(f"{a:.3f}" for (_, a) in tunings) + "];")
lines.append("// tuning detents: " +
             ", ".join(f"{l}={a:.1f}" for (l, a) in tunings))

# ---- stray-light vane: start it where the diffracted fan has passed ----
# The vane is a full-height wall at by = 25 separating the snout region
# from the camera corridor. beam3 must cross by = 25, so the vane can only
# begin downstream of the crossing plus the fan half-width plus margin.
import mech
guard_dims = {k: CHOSEN[k] for k in ("colD", "camD", "grat_w", "slab1_w",
                                     "slab2_w", "flat4_d", "km100_modules",
                                     "km100_scallop_half") if k in CHOSEN}
VANE_Y, VANE_T, VANE_END = 25.0, 3.0, 68.0
gb, c2b2 = b(d.G), bdir(d.c2)
t_cross = (VANE_Y - gb[1]) / c2b2[1]
bx_cross = gb[0] + t_cross * c2b2[0]
# fan radius at the crossing (same model as mech.py beams)
_dm = dict(mech.DIMS); _dm.update(guard_dims)
u_fan = 1.0 / (2.0 * _dm["fnum"]) + _dm["lam_nm"] * 1e-6 / (
    _dm["slit_w_um"] * 1e-3)
_ca = abs(dot(d.c1, d.gr.n)); _cb = abs(dot(d.c2, d.gr.n))
r_fan = min(min(d.rfl1 * u_fan, 0.9 * _dm["colD"] / 2.0) / _ca,
            _dm["grat_w"] / 2.0) * _cb + t_cross * (
    _dm["band_nm"] * 1e-6 / (d.sigma * _cb))
vane_x0 = math.ceil(bx_cross + r_fan / abs(c2b2[1]) + 4.0)
lines.append(f"vaneX0 = {vane_x0:.1f};  // vane start: beam3 fan crosses "
             f"by={VANE_Y:.0f} at bx={bx_cross:.1f}, fan r={r_fan:.1f}")

# ---- clearance guard: full pairwise interference check (mech.py) ----
# Beams are modeled at their aperture-clamped Fraunhofer fan width, not as
# chief rays. Any negative clearance aborts the export.
guard_dims["vane"] = (vane_x0, VANE_END, VANE_Y, VANE_T)
mech.assert_clear(d, margin=3.0, dims=guard_dims)

with open("body_geom.scad", "w") as f:
    f.write("\n".join(lines) + "\n")
print("\n".join(lines))
