// AUTO-GENERATED by body_export.py from raytrace.py CHOSEN geometry.
// config B_edmund_30s-45 dev=20.0 s2=-1.0 Lg=117.0 Lc=240.0 (built at Ha 656.28)
slitP   = [0.00, 0.00];
oap1P   = [81.79, 0.00];
gratP   = [-19.53, -58.50];
oap2P   = [134.73, 125.35];
sensP   = [-43.12, 109.79];
c0Ang   = 0.000;   // slit -> OAP1 chief
c1Ang   = -150.000;   // OAP1 -> grating (collimated)
c2Ang   = 50.000;   // grating -> OAP2 (diffracted)
dfAng   = -175.000;   // OAP2 -> sensor (focused)
gratNormAng = 93.100; // grating normal at Ha tuning
rfl1 = 81.79; rfl2 = 178.53;
// Ha incidence alpha=63.1 beta=43.1
gratNormAngs = [68.641, 93.100, 81.286];
// tuning detents: CaK=68.6, Ha=93.1, He1083=81.3
