#!/usr/bin/env python3
"""Export the CHOSEN raytrace geometry as OpenSCAD constants (body_geom.scad).

Body coordinate convention (matches layout.png):
  bx = world z   (toward OAP1)
  by = world y   (fold/dispersion plane)
  bz = world x   (slit length / grating grooves) -> vertical, deck normal.

Run: .venv/bin/python body_export.py
"""

import math
from raytrace import Design, CONFIGS, CHOSEN, dot

cfg = CONFIGS[CHOSEN["config"]]
d = Design(lines_per_mm=2400.0, order=1, dev=CHOSEN["dev"], s2=CHOSEN["s2"],
           Lg=CHOSEN["Lg"], Lc=CHOSEN["Lc"], **cfg)
d.build(656.28)


def b(p):  # world (x,y,z) -> body (bx,by)
    return (p[2], p[1])


def bdir(v):
    n = math.hypot(v[2], v[1])
    return (v[2] / n, v[1] / n)


def ang(v):  # body-plane angle of a direction, degrees, atan2(by,bx)
    return math.degrees(math.atan2(v[1], v[2]))


lines = [
    "// AUTO-GENERATED by body_export.py from raytrace.py CHOSEN geometry.",
    f"// config {CHOSEN['config']} dev={CHOSEN['dev']} s2={CHOSEN['s2']} "
    f"Lg={CHOSEN['Lg']} Lc={CHOSEN['Lc']} (built at Ha 656.28)",
    f"slitP   = [{b(d.S)[0]:.2f}, {b(d.S)[1]:.2f}];",
    f"oap1P   = [{b(d.C1)[0]:.2f}, {b(d.C1)[1]:.2f}];",
    f"gratP   = [{b(d.G)[0]:.2f}, {b(d.G)[1]:.2f}];",
    f"oap2P   = [{b(d.C2)[0]:.2f}, {b(d.C2)[1]:.2f}];",
    f"sensP   = [{b(d.F2)[0]:.2f}, {b(d.F2)[1]:.2f}];",
    f"c0Ang   = {ang(d.c0):.3f};   // slit -> OAP1 chief",
    f"c1Ang   = {ang(d.c1):.3f};   // OAP1 -> grating (collimated)",
    f"c2Ang   = {ang(d.c2):.3f};   // grating -> OAP2 (diffracted)",
    f"dfAng   = {ang(d.df):.3f};   // OAP2 -> sensor (focused)",
    f"gratNormAng = {ang(d.gr.n):.3f}; // grating normal at Ha tuning",
    f"rfl1 = {cfg['rfl1']}; rfl2 = {cfg['rfl2']};",
]
alpha = math.degrees(math.acos(abs(dot(d.c1, d.gr.n))))
beta = math.degrees(math.acos(abs(dot(d.c2, d.gr.n))))
lines.append(f"// Ha incidence alpha={alpha:.1f} beta={beta:.1f}")

# per-line grating normal angles (tuning positions for the rotator detents)
tunings = []
for (label, lam, lpmm) in [("CaK", 393.37, 2400.0), ("Ha", 656.28, 2400.0),
                           ("He1083", 1083.0, 1200.0)]:
    dl = Design(lines_per_mm=lpmm, order=1, dev=CHOSEN["dev"],
                s2=CHOSEN["s2"], Lg=CHOSEN["Lg"], Lc=CHOSEN["Lc"], **cfg)
    dl.build(lam)
    tunings.append((label, ang(dl.gr.n)))
lines.append("gratNormAngs = [" +
             ", ".join(f"{a:.3f}" for (_, a) in tunings) + "];")
lines.append("// tuning detents: " +
             ", ".join(f"{l}={a:.1f}" for (l, a) in tunings))

# ---- clearance guard: diffracted beam vs OAP1 mount slab ----
import sys
SLABW, SLAB1SHIFT, BEAM_D = 150.0, 34.0, 19.0
f1 = (b(d.C1)[0] - 45.0 * math.cos(math.radians(ang(d.c1))),
      b(d.C1)[1] - 45.0 * math.sin(math.radians(ang(d.c1))))
ta = math.radians(ang(d.c1) + 90)
tg, gp = (math.cos(ta), math.sin(ta)), b(d.G)
c2b = (math.cos(math.radians(ang(d.c2))), math.sin(math.radians(ang(d.c2))))
# solve gp + t*c2b = f1 + s*tg (face-plane crossing)
det = c2b[0] * (-tg[1]) - c2b[1] * (-tg[0])
rx, ry = f1[0] - gp[0], f1[1] - gp[1]
t = (rx * (-tg[1]) - ry * (-tg[0])) / det
s = (c2b[0] * ry - c2b[1] * rx) / det
lo, hi = SLAB1SHIFT - SLABW / 2, SLAB1SHIFT + SLABW / 2
if s < lo:
    marg = (lo - s) - BEAM_D / 2          # clear below the slab edge
elif s > hi:
    marg = (s - hi) - BEAM_D / 2          # clear beyond the far edge
else:
    marg = -min(s - lo, hi - s)           # inside the slab: collision
print(f"// GUARD diffracted beam crosses OAP1 slab plane at s={s:.1f} "
      f"(slab spans [{lo:.0f},{hi:.0f}]) -> clearance {marg:.1f} mm")
if 0 <= marg < 5:
    print("// WARNING: <5 mm beam-to-slab clearance", file=sys.stderr)
if marg < 0:
    raise SystemExit("FATAL: diffracted beam intersects the OAP1 slab")

with open("body_geom.scad", "w") as f:
    f.write("\n".join(lines) + "\n")
print("\n".join(lines))
