// AUTO-GENERATED by body_export.py from raytrace.py CHOSEN geometry.
// config T_budget_ha dev=24.0 s2=-1.0 Lg=70.0 Lc=130.0 (built at Ha 656.28)
slitP   = [0.00, 0.00];
oap1P   = [50.80, 0.00];
gratP   = [1.30, -49.50];
oap2P   = [47.89, 71.87];
sensP   = [-16.75, 103.95];
c0Ang   = 0.000;   // slit -> OAP1 chief
c1Ang   = -135.000;   // OAP1 -> grating (collimated)
c2Ang   = 69.000;   // grating -> OAP2 (diffracted)
df0Ang  = -156.000;   // OAP2 -> fold flat (focused)
dfAng   = 114.000;   // final leg -> sensor
flat4P  = [5.87, 53.16];
flat4NormAng = 69.000; // seat face normal
gratNormAng = 110.623; // grating normal at Ha tuning
rfl1 = 50.8; rfl2 = 101.6;
// Ha incidence alpha=65.6 beta=41.6
gratNormAngs = [85.855, 110.623, 98.630];
// tuning detents: CaK=85.9, Ha=110.6, He1083=98.6
vaneX0 = 46.0;  // vane start: beam3 fan crosses by=25 at bx=29.9, fan r=10.6
