// =====================================================================
// GhostSun all-reflective SHG - CONSOLIDATED single-file model
// Generated from the repo sources (design/): body_geom.scad (raytrace
// export), shg_body.scad, mounts/kinematic_mount.scad.
// The repo remains the source of truth; regenerate this file with:
//   .venv/bin/python body_export.py && python make_all_scad.py
//
// part = "preview"          assembled body + rotor + ghost camera
//        "body"             the instrument body (print)
//        "rotor"            grating turntable (print)
//        "shelyak_adapter"  25x25 grating sleeve (print)
//        "km_base"          kinematic mount fixed plate (print x2)
//        "km_platform"      kinematic mount moving plate (print x2)
//
// Optics: Edmund #35-607 collimator + #35-588 camera, 20 deg off-Littrow,
// Lg=117 Lc=240. See design/RESULTS.md and design/BODY.md.
// =====================================================================

// ---- raytrace geometry (auto-generated) ----
// AUTO-GENERATED by body_export.py from raytrace.py CHOSEN geometry.
// config T_budget_ha dev=24.0 s2=-1.0 Lg=70.0 Lc=130.0 (built at Ha 656.28)
slitP   = [0.00, 0.00];
oap1P   = [50.80, 0.00];
gratP   = [1.30, -49.50];
oap2P   = [47.89, 71.87];
sensP   = [-16.75, 103.95];
c0Ang   = 0.000;   // slit -> OAP1 chief
c1Ang   = -135.000;   // OAP1 -> grating (collimated)
c2Ang   = 69.000;   // grating -> OAP2 (diffracted)
df0Ang  = -156.000;   // OAP2 -> fold flat (focused)
dfAng   = 114.000;   // final leg -> sensor
flat4P  = [5.87, 53.16];
flat4NormAng = 69.000; // seat face normal
gratNormAng = 110.623; // grating normal at Ha tuning
rfl1 = 50.8; rfl2 = 101.6;
// Ha incidence alpha=65.6 beta=41.6
gratNormAngs = [85.855, 110.623, 98.630];
// tuning detents: CaK=85.9, Ha=110.6, He1083=98.6
vaneX0 = 46.0;  // vane start: beam3 fan crosses by=25 at bx=29.9, fan r=10.6

// ---- instrument body ----
// GhostSun all-reflective SHG — instrument body.
// Optical anchors come from body_geom.scad (generated by body_export.py
// from the raytrace CHOSEN geometry). Do not hand-edit positions.
//
// Deck parallel to the fold plane, beams at beamH above deck. OAP kinematic
// bases (mounts/) bolt to angled wall slabs whose normals are the mirror
// substrate axes. Grating grooves are vertical -> tuning is a deck
// turntable with tangent-arm fine screw + arc clamp. Slit cartridge drops
// into the tower at the origin (tilted about vertical to dump the jaw
// reflection); an enclosed snout runs from the telescope flange to the
// slit. Camera tunnel runs from the front wall to the sensor plane.
//
// part = "body" | "rotor" | "shelyak_adapter" | "preview"


/* [Global] */
part = "preview";
deckT = 6;
wallT = 4;
wallH = 125;
beamH = 60;          // beam axis above deck (mirror-size KM plates)
margin = 38;

/* [Mirror mounts] */
mirrorStack = 45;    // optical face -> mount wall face
slabT = 14;
slab1W = 54;         // OAP1 slab (budget KM plate 48 + 6, Ø25.4 MPD124)
slab2W = 54;         // OAP2 slab (v3: Ø25.4 MPD144, KM plate 48)
km1Hole = 16;        // KM base bolt triangle half-pitch = plateW/2 - m/2
km2Hole = 16;        // (bossMargin m = 16 in mounts/)
m5insD = 6.4; m5insL = 12;

/* [Slit + snout] */
slitTilt = 10;
slitSlideW = 12; slitSlideH = 22; slitSlideT = 3.2;
snoutID = 30;  // entry bore snoutID-4 = 26 vs ~20 mm beam at the flange
scopeBoreD = 44; scopeFlangeD = 56;
scopeThreadD = 48; scopeThreadP = 0.75;  // M48x0.75 female (telescope side)
scopeThreadL = 9;
snoutExt = 50;       // external snout extension: moves the OTA's fat parts
                     // forward so the camera sits beside a Ø64 tube, not
                     // the Ø95 FSQ body. Beam at the far end ~30 mm.

/* [Camera port] */
camBoreD = 34; camTubeD = 56;
// prototype camera: ToupTek G3M678M — MEASURE and update (placeholder
// Ø40 x 70 body). Production IMX571: Ø80 body, Ø100x10 tilt flange, 108mm.
camFocD = 58; camFocL = 20;
camTiltD = 44; camTiltT = 4;
camBodyD = 40; camBodyL = 70;
camThreadD = 42; camThreadP = 0.75;  // M42x0.75 (T2) female, printed
camThreadL = 9; camThreadClr = 0.35; // radial print clearance

/* [Grating rotator] */
rotD = 56; pivotD = 8.05; tuneRange = 12;
armR = 70;           // M4x0.7 tangent at armR: 0.57 deg/turn
gratMax = 51; gratWinD = 40;

function u(a) = [cos(a), sin(a)];
eps = 0.01;
showBeams = true;    // draw the light path in part="preview"

// beam segment: frustum from p1 to p2 at beam height
module beam(p1, p2, d1, d2, col) {
    L = norm([p2[0] - p1[0], p2[1] - p1[1]]);
    a = atan2(p2[1] - p1[1], p2[0] - p1[0]);
    color(col, 0.45)
        translate([p1[0], p1[1], beamH]) rotate([0, 0, a]) rotate([0, 90, 0])
            cylinder(h = L, d1 = d1, d2 = d2, $fn = 48);
}

module light_path() {
    // telescope cone: front wall -> slit (converges to the slit)
    beam([minX - snoutExt, 0], slitP, 26, 0.8, "gold");
    // slit -> OAP1: diverging f/6.9 cone (+ field)
    beam(slitP, oap1P, 0.8, 16, "gold");
    // OAP1 -> grating: collimated, ~13 mm
    beam(oap1P, gratP, 13, 13, "orange");
    // grating -> OAP2: anamorphically widened (cos b / cos a ~ 1.6 at Ha)
    beam(gratP, oap2P, 19, 19, "red");
    // OAP2 -> sensor: converging to the spectrum image
    // OAP2 -> fold flat -> sensor (v3: fixed 45-deg flat seat)
    beam(oap2P, flat4P, 14, 8, "crimson");
    beam(flat4P, sensP, 8, 3, "crimson");
}

module deck_labels() {
    for (lp = [[slitP, "SLIT", 8], [oap1P, "OAP1", 10],
               [gratP, "GRATING", 10], [oap2P, "OAP2", 10],
               [sensP, "SENSOR", 8]])
        color("white") translate([lp[0][0], lp[0][1] - 14, 0.2])
            linear_extrude(0.8) text(lp[1], size = lp[2],
                                     halign = "center", font = "Liberation Sans:style=Bold");
}

// deck extents: optical features plus the mirror-slab corner points
slab1F = [oap1P[0] - mirrorStack * cos(c1Ang), oap1P[1] - mirrorStack * sin(c1Ang)];
slab2F = [oap2P[0] + mirrorStack * cos(c2Ang), oap2P[1] + mirrorStack * sin(c2Ang)];
function slabPts(f, a, w) = [for (s = [-1, 1], b = [0, 1])
    [f[0] + s * (w / 2) * cos(a + 90) - b * slabT * cos(a),
     f[1] + s * (w / 2) * sin(a + 90) - b * slabT * sin(a)]];
allPts = concat([slitP, gratP, sensP, flat4P, [0, 0]],
                slabPts(slab1F, c1Ang, slab1W),
                slabPts(slab2F, c2Ang + 180, slab2W),
                [[gratP[0], gratP[1] - rotD - 20]]);
minX = min([for (p = allPts) p[0]]) - margin;
maxX = max([for (p = allPts) p[0]]) + 8;
minY = min([for (p = allPts) p[1]]) - 8;
maxY = max([for (p = allPts) p[1]]) + 8;
// camera tunnel length: distance from the sensor plane to whichever
// wall the exit ray meets first (v3 exits the +Y wall, v2 exited -X)
camExit = min(
    u(dfAng)[0] < 0 ? (sensP[0] - minX) / -u(dfAng)[0] :
    u(dfAng)[0] > 0 ? (maxX - sensP[0]) / u(dfAng)[0] : 1e9,
    u(dfAng)[1] < 0 ? (sensP[1] - minY) / -u(dfAng)[1] :
    u(dfAng)[1] > 0 ? (maxY - sensP[1]) / u(dfAng)[1] : 1e9);
armAng = gratNormAng + 270;          // rotor arm at Ha tuning
armAngs = [for (a = gratNormAngs) a + 270];   // per-line detents
armLo = min(armAngs) - 3; armHi = max(armAngs) + 3;

// Male thread form, used directly or as a cutter for female threads.
// Twisted-lobe method: 240-deg lobe -> ~55-60 deg included flank angle.
module thread_male(d, pitch, len) {
    hth = 0.6495 * pitch;
    rmin = d / 2 - hth;
    pts = [for (a = [0:6:359])
        let (t = abs(((a + 180) % 360) - 180),
             f = min(0.92, max(0, 1 - t / 120)))
        [(rmin + f * hth) * cos(a), (rmin + f * hth) * sin(a)]];
    linear_extrude(len, twist = -360 * len / pitch,
                   slices = ceil(len / pitch) * 24, convexity = 10)
        polygon(pts);
    cylinder(h = len, d = 2 * rmin + 0.2, $fn = 96);
}

module mirror_slab(faceP, normAng, w, hole) {
    difference() {
        linear_extrude(wallH)
            translate(faceP) rotate([0, 0, normAng])
                translate([-slabT / 2, 0]) square([slabT, w], center = true);
        for (hv = [[hole, hole], [hole, -hole], [-hole, hole]])
            translate([faceP[0], faceP[1], beamH + hv[1]])
                rotate([0, 0, normAng]) rotate([0, 90, 0])
                    translate([0, hv[0], -m5insL])
                        cylinder(h = m5insL + eps, d = m5insD, $fn = 32);
    }
}

module along(p2, a) {  // place children at beamH, local +z along angle a
    translate([p2[0], p2[1], beamH]) rotate([0, 0, a]) rotate([0, 90, 0])
        children();
}

module body() {
    camLen = camExit;  // sensor plane -> exit wall
    veeX = gratP[0] + (25 - gratP[1]) / u(c2Ang)[1] * u(c2Ang)[0];
    difference() {
        union() {
            translate([minX, minY, -deckT])
                cube([maxX - minX, maxY - minY, deckT]);
            linear_extrude(wallH) difference() {
                translate([minX, minY]) square([maxX - minX, maxY - minY]);
                translate([minX + wallT, minY + wallT])
                    square([maxX - minX - 2 * wallT, maxY - minY - 2 * wallT]);
            }
            mirror_slab(slab1F, c1Ang, slab1W, km1Hole);
            mirror_slab(slab2F, c2Ang + 180, slab2W, km2Hole);
            // slit tower: asymmetric footprint (MECH.md). The
            // downstream face at bx=+4 is a thin blade wall (flock it:
            // the diffracted fan passes just beyond), and the across-beam
            // width is the cartridge minimum, not the old +-17.
            linear_extrude(beamH + slitSlideH)
                translate([-10, -10]) square([14, 20]);
            // snout: front wall -> slit tower (enclosed square tunnel)
            translate([minX, -snoutID / 2 - wallT, beamH - snoutID / 2 - wallT])
                cube([-minX - 8, snoutID + 2 * wallT, snoutID + 2 * wallT]);
            // telescope snout extension + flange (exterior)
            along([minX, 0], 180)
                cylinder(h = snoutExt, d = scopeFlangeD, $fn = 96);
            // camera tunnel: sensor plane -> through front wall + flange
            along(sensP, dfAng) cylinder(h = camLen + 10, d = camTubeD, $fn = 96);
            // fold-flat seat: fixed 45-deg block. fold_tol.py: flat
            // tilt is pure image steering (tolerance unbounded), so the
            // O25.4 flat is clamped in a plain pocket, no adjusters.
            translate([flat4P[0], flat4P[1], 0])
                rotate([0, 0, flat4NormAng]) difference() {
                    translate([-16, -19, 0])
                        cube([16, 38, beamH + 20]);
                    translate([0, 0, beamH]) rotate([0, 90, 0]) {
                        translate([0, 0, -6.2])
                            cylinder(h = 6.4, d = 25.8, $fn = 96);
                        translate([0, 0, -0.4])
                            cylinder(h = 3, d1 = 22, d2 = 30, $fn = 96);
                    }
                    // radial nylon-tip grub screws (M3) to clamp the flat
                    for (a = [90, 210, 330])
                        translate([-3.2, 0, beamH]) rotate([a, 0, 0])
                            rotate([0, 90, 0])
                                cylinder(h = 30, d = 2.7, $fn = 24);
                }
            // grating turntable seat
            translate([gratP[0], gratP[1], 0])
                cylinder(h = 6, d = rotD + 10, $fn = 96);
            // tangent-screw posts: one per line detent (CaK / He / Ha)
            for (a = armAngs)
                translate([gratP[0] + (armR + 14) * u(a)[0],
                           gratP[1] + (armR + 14) * u(a)[1], 0])
                    cylinder(h = 22, d = 16, $fn = 48);
            // stray-light vane at by = +25: separates the slit/snout
            // region from the camera corridor. Ends at bx=68 — beyond
            // that the OAP1 mount slab is the separator, and the mirror
            // substrate envelope must stay clear.
            linear_extrude(wallH)
                translate([vaneX0, 25])
                    square([68 - vaneX0, 3]);
        }
        // slit cartridge pocket + optical opening (tilted about vertical)
        translate([0, 0, beamH]) rotate([0, 0, slitTilt]) {
            translate([0, 0, slitSlideH / 2])
                cube([slitSlideT, slitSlideW, 3 * slitSlideH], center = true);
            rotate([0, 90, 0])
                cylinder(h = 44, d = 9, center = true, $fn = 48);
        }
        // snout bore (stops at slit tower wall)
        translate([minX - 20, 0, beamH]) rotate([0, 90, 90]) rotate([0, 90, 0])
            cylinder(h = -minX + 20 - 6, d = snoutID - 4, $fn = 64);
        // telescope bore through extension + front wall, stepped behind
        // the M48x0.75 female thread at the far face
        along([minX + 16, 0], 180)
            cylinder(h = snoutExt + 40, d = scopeBoreD, $fn = 96);
        along([minX, 0], 180) translate([0, 0, snoutExt - scopeThreadL]) {
            thread_male(scopeThreadD + 2 * camThreadClr, scopeThreadP,
                        scopeThreadL + 1);
            translate([0, 0, scopeThreadL - 0.8])
                cylinder(h = 2, d1 = scopeThreadD - 1,
                         d2 = scopeThreadD + 1.6, $fn = 96);
        }
        // camera bore along df through tunnel, wall, flange
        along(sensP, dfAng)
            translate([0, 0, -6]) cylinder(h = camLen + 30 - camThreadL, d = camBoreD, $fn = 96);
        // M42x0.75 female thread at the exterior end (focuser interface):
        // cut with an oversized male form + entry chamfer
        along(sensP, dfAng) translate([0, 0, camLen + 10 - camThreadL]) {
            thread_male(camThreadD + 2 * camThreadClr, camThreadP,
                        camThreadL + 1);
            translate([0, 0, camThreadL - 0.8])
                cylinder(h = 2, d1 = camThreadD - 1, d2 = camThreadD + 1.6,
                         $fn = 96);
        }
        // grating pivot + clamp arc slot (centered on the arm direction)
        translate([gratP[0], gratP[1], -deckT - 1])
            cylinder(h = 40, d = pivotD, $fn = 48);
        translate([gratP[0], gratP[1], -deckT - 1])
            rotate([0, 0, armLo])
                rotate_extrude(angle = armHi - armLo, $fn = 256)
                    translate([armR - 12, 0]) square([4.3, 40]);
        // tangent screw: horizontal M4 insert through the post, aimed
        // tangentially (perpendicular to the arm) at the arm tip
        for (a = armAngs)
            translate([gratP[0] + (armR + 14) * u(a)[0],
                       gratP[1] + (armR + 14) * u(a)[1], 14])
                rotate([0, 0, a + 90]) rotate([0, 90, 0])
                    translate([0, 0, -20]) cylinder(h = 40, d = 3.4, $fn = 24);
        // vane aperture where the diffracted beam crosses by = 25
        translate([veeX, 25, beamH]) rotate([0, 0, c2Ang]) rotate([0, 90, 0])
            cylinder(h = 40, d = 32, center = true, $fn = 64);
    }
}

module rotor() {
    difference() {
        union() {
            cylinder(h = 8, d = rotD, $fn = 128);
            translate([-gratMax / 2 - 3, -3.5, 0])
                cube([gratMax + 6, 16, 8 + gratMax + 8]);
            rotate([0, 0, 180]) translate([0, -6, 0]) cube([armR, 12, 8]);
        }
        translate([0, 0, -1]) cylinder(h = 80, d = pivotD, $fn = 48);
        // grating slot, slide-in from top; front face registers on the
        // pivot-axis plane (y=0 local)
        translate([-gratMax / 2, 0, 8]) cube([gratMax, 10.2, gratMax + 9]);
        translate([0, -5, 8 + 4 + gratMax / 2]) rotate([90, 0, 0])
            cylinder(h = 20, d = gratWinD, center = true, $fn = 96);
        // rear nylon-tip clamp screw
        translate([0, 8, 8 + 4 + gratMax / 2]) rotate([-90, 0, 0])
            cylinder(h = 20, d = 4.4, $fn = 24);
        // clamp thumbscrew through the arm at armR-10 (into deck arc slot)
        rotate([0, 0, 180]) translate([armR - 10, 0, -1])
            cylinder(h = 12, d = 4.4, $fn = 24);
    }
}

module shelyak_adapter() {
    difference() {
        cube([gratMax - 0.4, 9.8, gratMax - 0.4]);
        translate([(gratMax - 25.6) / 2, -1, (gratMax - 25.6) / 2])
            cube([25.6, 7.2, 25.6]);
        translate([(gratMax - 0.4) / 2, 12, (gratMax - 0.4) / 2])
            rotate([90, 0, 0]) cylinder(h = 20, d = 22, $fn = 64);
    }
}

// ghost optics: mirror substrates at their traced positions/normals
showOptics = true;
function bis(a_in, a_out) = atan2(sin(a_out) - sin(a_in),
                                  cos(a_out) - cos(a_in));
module optics_ghost() {
    // OAP1 (MPD124): face normal bisects slit->OAP1 and OAP1->grating
    color("lightsteelblue", 0.9) along(oap1P, bis(c0Ang, c1Ang) + 180)
        cylinder(h = 8, d = 25.4, $fn = 64);
    // OAP2 (MPD144)
    color("lightsteelblue", 0.9) along(oap2P, bis(c2Ang, df0Ang) + 180)
        cylinder(h = 8, d = 25.4, $fn = 64);
    // fold flat (PF10-03-P01) seated in its pocket
    color("aliceblue", 0.9) along(flat4P, flat4NormAng + 180)
        cylinder(h = 6, d = 25.4, $fn = 64);
    // Shelyak grating 25 x 25 x 6 on the rotor
    color("mediumblue", 0.9) along(gratP, gratNormAng + 180)
        translate([-12.5, -12.5, 0]) cube([25, 25, 6]);
}

// ghost camera envelope (reference only, renders transparent)
module camera_ghost() {
    camLenG = camExit;
    %along(sensP, dfAng) translate([0, 0, camLenG + 10]) {
        cylinder(h = camFocL, d = camFocD, $fn = 64);
        translate([0, 0, camFocL]) cylinder(h = camTiltT, d = camTiltD, $fn = 64);
        translate([0, 0, camFocL + camTiltT])
            cylinder(h = camBodyL, d = camBodyD, $fn = 64);
    }
}

if (part == "body" || part == "preview") body();
if (part == "preview") {
    camera_ghost();
    deck_labels();
    if (showOptics) optics_ghost();
    if (showBeams) light_path();
}
if (part == "rotor") rotor();
if (part == "preview")
    translate([gratP[0], gratP[1], 6.2]) rotate([0, 0, armAng - 180]) rotor();
if (part == "shelyak_adapter") shelyak_adapter();

// ---- printable kinematic OAP mount ----
// GhostSun SHG — printable kinematic OAP mount (OpenSCAD twin of the
// Fusion 360 script; same parameter names and geometry).
//
// Kinematics: cone / vee / flat. Fixed pivot ball glued into the platform
// pocket rides the base CONE; adjuster screw at adjA lands in the VEE
// (pitch); adjuster screw at adjB lands on the FLAT (yaw). Two steel
// extension springs preload the plates together.
//
// Angular resolution: deg per turn = atan(screw_pitch / leverArm).
//   leverArm=120, M4x0.7:  0.33 deg/turn (20 arcmin) -> 1/20 turn = 1'
//   leverArm=120, 100TPI:  0.12 deg/turn ( 7 arcmin) -> 1/20 turn = 0.36'
// OAP yaw tolerance from raytrace: 1.5 arcmin. Lock after alignment.
//
// Print ASA/PC/annealed PETG, 6+ perimeters, plates flat on the bed.

/* [Kinematics] */
// Plates are MIRROR-SIZED; fine resolution comes from 100 TPI adjusters,
// not lever length. deg/turn = atan(pitch / leverArm):
//   OAP1 plate 80 (lever 48):  100TPI 0.30 deg/turn (18'/turn)
//   OAP2 plate 105 (lever 73): 100TPI 0.20 deg/turn (12'/turn)
// vs 1.5 arcmin yaw tolerance: 1/12 - 1/8 turn per tolerance step; use
// lock nuts. M4x0.7 is NOT sufficient at these levers.
leverArm = 73;       // pivot-to-adjuster distance (= plateW - 2*bossMargin)
gap = 10;            // assembled plate separation
ballD = 6;           // steel balls (pivot + screw tips)

/* [Plates] */
plateW = 105;        // print OAP1 pair at 80, OAP2 pair at 105
plateH = 105;
plateT = 8;
bossMargin = 16;     // corner margin / boss diameter

/* [Hardware] */
insertD = 5.6;       // M4 heat-set insert hole
insertL = 8;
springHoleD = 3.2;
mirrorBCD = 40;      // backing-plate bolt circle (measure your mirror!)
mirrorOffX = 0;      // mirror center offset along X (normally 0)
mirrorBoltD = 4.4;
mirrorBoltN = 3;
baseBoltD = 5.4;     // M5 to housing
baseCboreD = 10;
baseCboreZ = 4;

/* [Swappability] */
label = "OAP1-AU";   // embossed on the platform edge (station + coating)
liftTabW = 22;       // finger tab on the platform's free corner
keyFence = true;     // corner fence on the base: platform seats one way only

part = "both";       // both | base | platform | base_cap

m = bossMargin;
pivot = [m, m];
adjA  = [m, m + leverArm];   // vee -> pitch
adjB  = [m + leverArm, m];   // flat -> yaw
springs = [[m + 0.35*leverArm, m + 0.35*leverArm],
           [m + 0.60*leverArm, m + 0.60*leverArm]];
centroid = [(pivot[0]+adjA[0]+adjB[0])/3 + mirrorOffX, (pivot[1]+adjA[1]+adjB[1])/3];

module km_plate() { cube([plateW, plateH, plateT]); }

module km_at(p) { translate([p[0], p[1], 0]) children(); }

module cone_seat() {            // 120-deg included cone, mouth 0.9*ballD
    mouth = 0.9 * ballD;
    depth = (mouth/2) / tan(60);
    translate([0, 0, plateT - depth + 0.01])
        cylinder(h = depth, d1 = 0, d2 = mouth, $fn = 64);
}

module vee_groove() {           // 90-deg vee aimed at the cone (along Y)
    w = 0.8 * ballD; l = bossMargin;
    translate([0, 0, plateT])
        rotate([0, 45, 0])      // square prism on its edge
            cube([w/sqrt(2), l, w/sqrt(2)], center = true);
}

module km_base() {
    // corner fence: the platform seats in one orientation only
    if (keyFence)
        for (f = [[plateW-3, -3, 3, plateH*0.4], [-3, plateH-3, plateW*0.4, 3]])
            translate([f[0], f[1], 0]) cube([f[2], f[3], plateT + gap*0.6]);
    difference() {
        km_plate();
        km_at(pivot) cone_seat();
        km_at(adjA) vee_groove();
        // flat at adjB: untouched surface
        for (s = springs) km_at(s) cylinder(h=3*plateT, d=springHoleD, center=true, $fn=32);
        for (c = [[plateW-m/2, plateH-m/2], [plateW-m/2, m/2], [m/2, plateH-m/2]]) {
            km_at(c) cylinder(h=3*plateT, d=baseBoltD, center=true, $fn=32);
            km_at(c) cylinder(h=baseCboreZ, d=baseCboreD, $fn=32);
        }
    }
}

module km_platform() {
    difference() {
        union() {
            km_plate();
            // lift tab on the free corner: tool-free module removal
            translate([plateW - 2, plateH - liftTabW - 4, 0])
                cube([14, liftTabW, plateT]);
        }
        // grip grooves on the tab
        for (g = [0:2])
            translate([plateW + 4 + g*3, plateH - liftTabW - 5, plateT - 1.2])
                cube([1.4, liftTabW + 2, 2]);
        // embossed module label on the front edge (station + coating)
        translate([plateW*0.32, 1.2, plateT*0.25]) rotate([90,0,0])
            linear_extrude(1.4) text(label, size=plateT*0.5,
                font="Liberation Sans:style=Bold");
        // pivot ball press-fit pocket (glue), half-ball deep
        km_at(pivot) translate([0,0,plateT-ballD/2])
            cylinder(h=ballD/2+0.01, d=0.98*ballD, $fn=64);
        // adjuster heat-set insert holes (screws pass through to base side)
        for (a = [adjA, adjB]) {
            km_at(a) cylinder(h=3*plateT, d=4.4, center=true, $fn=32);
            km_at(a) translate([0,0,plateT-insertL])
                cylinder(h=insertL+0.01, d=insertD, $fn=32);
        }
        // OPEN spring hooks: keyhole slots run to the plate edge so the
        // springs unhook sideways without tools (fast module swap)
        for (s = springs) {
            km_at(s) cylinder(h=3*plateT, d=springHoleD, center=true, $fn=32);
            km_at(s) translate([-springHoleD/2, -plateH, -plateT])
                cube([springHoleD, plateH, 3*plateT]);
        }
        // mirror backing-plate bolt circle at support-triangle centroid
        for (k = [0 : mirrorBoltN-1])
            km_at([centroid[0] + mirrorBCD/2*cos(360*k/mirrorBoltN),
                centroid[1] + mirrorBCD/2*sin(360*k/mirrorBoltN)])
                cylinder(h=3*plateT, d=mirrorBoltD, center=true, $fn=32);
    }
}

// snap-on dust cap protecting the cone/vee/flat seats while a module
// is off the instrument (grit in the vee costs arcminutes)
module base_cap() {
    difference() {
        translate([-2, -2, 0]) cube([plateW*0.75, plateH*0.75, 3]);
        translate([2, 2, -1]) cube([plateW*0.75-8, plateH*0.75-8, 3]);
    }
    for (p = [pivot, adjA, adjB])
        at(p) cylinder(h=6, d=ballD*2.2, $fn=48);
}

if (part == "base_cap") base_cap();
if (part == "km_base") km_base();
if (part == "km_platform") km_platform();
