#!/usr/bin/env python3
"""Emit prod_layout.scad: raytraced-geometry visualization of the
two-level production periscope design (FOLDS.md winner) with the FSQ-85
OTA and the IMX571 camera at 17.5 mm back focus. Elements and SOLID
full-fan-width light paths; layout render, not the case CAD."""
import math
from raytrace import Design, CONFIGS, add, sub, mul, dot, norm

cfg = CONFIGS["B_edmund_30s-45"]
d = Design(lines_per_mm=2400.0, order=1, dev=17.0, s2=-1.0,
           Lg=315.0, Lc=255.0, lift2=dict(s=65.0, h=80.0), **cfg)
d.build(656.28)

BH = 60.0


def P(p):   # world (x=vert, y, z) -> model (X=z, Y=y, Z=x+BH)
    return (p[2], p[1], p[0] + BH)


u = 1.0 / (2.0 * 6.9) + 656.28e-6 / 7e-3
r_col = min(d.rfl1 * u, 0.9 * 50.8 / 2)
ca, cb = abs(dot(d.c1, d.gr.n)), abs(dot(d.c2, d.gr.n))
r3 = min(r_col / ca, 25.0) * cb
r3b = min(r3 + d.Lc * (5e-6 / (d.sigma * cb)), 0.9 * 76.2 / 2)
QA, QB = d.lift2A[0], d.lift2B[0]

out = ["// AUTO-GENERATED by prod_layout.py",
       "$fn = 72;",
       "module beam(a, b, r1, r2, col) { color(col, 0.5) hull() {",
       "  translate(a) sphere(r1); translate(b) sphere(r2); } }",
       "module disc(p, n, dia, t, col, alpha = 1.0) {",
       "  color(col, alpha) translate(p)",
       "    rotate(a = acos(n[2] / norm(n)), v = (abs(n[0]) + abs(n[1])",
       "      < 1e-6) ? [1, 0, 0] : [-n[1], n[0], 0])",
       "    cylinder(h = t, d = dia, center = true); }"]


def disc(p_model, n_world, dia, t, col, alpha=1.0):
    n = (n_world[2], n_world[1], n_world[0])
    out.append(f"disc([{p_model[0]:.1f},{p_model[1]:.1f},{p_model[2]:.1f}],"
               f" [{n[0]:.4f},{n[1]:.4f},{n[2]:.4f}], {dia}, {t}, "
               f"\"{col}\", {alpha});")


def beam(a, b, r1, r2, col):
    pa, pb = P(a), P(b)
    out.append(f"beam([{pa[0]:.1f},{pa[1]:.1f},{pa[2]:.1f}], "
               f"[{pb[0]:.1f},{pb[1]:.1f},{pb[2]:.1f}], {r1:.1f}, {r2:.1f},"
               f" \"{col}\");")


# level cue: slim posts under the upper-level elements
for p in (d.G, d.C2):
    q = P(p)
    out.append(f"color(\"dimgray\", 0.6) translate([{q[0]:.0f}, {q[1]:.0f},"
               f" 0]) cylinder(h = {q[2]-30:.0f}, d = 8);")

# light path
beam(add(d.S, (0.0, 0.0, -180.0)), d.S, 24.0, 0.6, "gold")
beam(d.S, d.C1, 0.6, r_col, "gold")
beam(d.C1, QA, r_col, r_col, "orange")
beam(QA, QB, r_col, r_col, "mediumpurple")
beam(QB, d.G, r_col, r_col, "orange")
beam(d.G, d.C2, r3, r3b, "red")
beam(d.C2, d.F2, r3b, 1.0, "crimson")

# elements
disc(P(d.S), (0.0, 0.0, 1.0), 18, 2, "green")
disc(P(d.C1), norm(sub(norm(sub((0, 0, 0), d.C1)), d.c1)), 50.8, 10,
     "orangered")
disc(P(QA), d.lift2A[1], 50.8, 9, "silver")
disc(P(QB), d.lift2B[1], 50.8, 9, "silver")
disc(P(d.G), d.gr.n, 55, 9, "royalblue")
disc(P(d.C2), norm(sub(d.df, d.c2)), 76.2, 12, "orangered")

# FSQ-85 OTA on the entry axis (focal plane = slit)
for (z0, z1, dia, col) in ((-620, -520, 112, "lightsteelblue"),
                           (-520, -190, 95, "white"),
                           (-190, -130, 72, "gainsboro"),
                           (-130, -88, 64, "silver"),
                           (-88, -40, 56, "dimgray")):
    out.append(f"color(\"{col}\") translate([{z0}, 0, {BH}]) "
               f"rotate([0, 90, 0]) cylinder(h = {z1 - z0}, d = {dia});")

# IMX571 camera: flange 10 mm thick ending 17.5 mm before the sensor,
# then the 80 mm barrel; sensor plane marked black
disc(P(d.F2), mul(d.df, -1.0), 26, 2, "black")
disc(P(add(d.F2, mul(d.df, -12.5))), d.df, 100, 10, "darkslategray")
disc(P(add(d.F2, mul(d.df, 46.5))), d.df, 80, 108, "dimgray")
open("prod_layout.scad", "w").write("\n".join(out) + "\n")
print("written; F2 model", [round(v) for v in P(d.F2)],
      "G", [round(v) for v in P(d.G)])
