// AUTO-GENERATED by prod_layout.py
$fn = 72;
module beam(a, b, r1, r2, col) { color(col, 0.5) hull() {
  translate(a) sphere(r1); translate(b) sphere(r2); } }
module disc(p, n, dia, t, col, alpha = 1.0) {
  color(col, alpha) translate(p)
    rotate(a = acos(n[2] / norm(n)), v = (abs(n[0]) + abs(n[1])
      < 1e-6) ? [1, 0, 0] : [-n[1], n[0], 0])
    cylinder(h = t, d = dia, center = true); }
color("dimgray", 0.6) translate([-122, -117, 0]) cylinder(h = 110, d = 8);
color("dimgray", 0.6) translate([52, 69, 0]) cylinder(h = 110, d = 8);
beam([-180.0,0.0,60.0], [0.0,0.0,60.0], 24.0, 0.6, "gold");
beam([0.0,0.0,60.0], [81.8,0.0,60.0], 0.6, 13.6, "gold");
beam([81.8,0.0,60.0], [25.5,-32.5,60.0], 13.6, 13.6, "orange");
beam([25.5,-32.5,60.0], [25.5,-32.5,140.0], 13.6, 13.6, "mediumpurple");
beam([25.5,-32.5,140.0], [-121.7,-117.5,140.0], 13.6, 13.6, "orange");
beam([-121.7,-117.5,140.0], [52.2,69.0,140.0], 17.9, 22.2, "red");
beam([52.2,69.0,140.0], [-126.2,62.8,140.0], 22.2, 1.0, "crimson");
disc([0.0,0.0,60.0], [1.0000,0.0000,0.0000], 18, 2, "green", 1.0);
disc([81.8,0.0,60.0], [-0.2588,0.9659,0.0000], 50.8, 10, "orangered", 1.0);
disc([25.5,-32.5,60.0], [0.6124,0.3536,0.7071], 50.8, 9, "silver", 1.0);
disc([25.5,-32.5,140.0], [-0.6124,-0.3536,-0.7071], 50.8, 9, "silver", 1.0);
disc([-121.7,-117.5,140.0], [-0.0223,0.9998,-0.0000], 55, 9, "royalblue", 1.0);
disc([52.2,69.0,140.0], [-0.9100,-0.4147,0.0000], 76.2, 12, "orangered", 1.0);
color("lightsteelblue") translate([-620, 0, 60.0]) rotate([0, 90, 0]) cylinder(h = 100, d = 112);
color("white") translate([-520, 0, 60.0]) rotate([0, 90, 0]) cylinder(h = 330, d = 95);
color("gainsboro") translate([-190, 0, 60.0]) rotate([0, 90, 0]) cylinder(h = 60, d = 72);
color("silver") translate([-130, 0, 60.0]) rotate([0, 90, 0]) cylinder(h = 42, d = 64);
color("dimgray") translate([-88, 0, 60.0]) rotate([0, 90, 0]) cylinder(h = 48, d = 56);
disc([-126.2,62.8,140.0], [0.9994,0.0349,-0.0000], 26, 2, "black", 1.0);
disc([-113.7,63.2,140.0], [-0.9994,-0.0349,0.0000], 100, 10, "darkslategray", 1.0);
disc([-172.7,61.1,140.0], [-0.9994,-0.0349,0.0000], 80, 108, "dimgray", 1.0);
