// GhostSun all-reflective SHG — instrument body.
// Optical anchors come from body_geom.scad (generated by body_export.py
// from the raytrace CHOSEN geometry). Do not hand-edit positions.
//
// Deck parallel to the fold plane, beams at beamH above deck. OAP kinematic
// bases (mounts/) bolt to angled wall slabs whose normals are the mirror
// substrate axes. Grating grooves are vertical -> tuning is a deck
// turntable with tangent-arm fine screw + arc clamp. Slit cartridge drops
// into the tower at the origin (tilted about vertical to dump the jaw
// reflection); an enclosed snout runs from the telescope flange to the
// slit. Camera tunnel runs from the front wall to the sensor plane.
//
// part = "body" | "rotor" | "shelyak_adapter" | "preview"

include <body_geom.scad>;

/* [Global] */
part = "preview";
deckT = 6;
wallT = 4;
wallH = 125;
beamH = 60;          // beam axis above deck (mirror-size KM plates)
margin = 38;

/* [Mirror mounts] */
mirrorStack = 45;    // optical face -> mount wall face
slabT = 14;
slab1W = 86;         // OAP1 slab (KM plate 80 + 6): mirror-sized plates
slab2W = 86;         // OAP2 slab (Ø50.8 mirror, KM plate 80)
km1Hole = 32;        // KM base bolt triangle half-pitch = plateW/2 - m/2
km2Hole = 32;        // (bossMargin m = 16 in mounts/)
m5insD = 6.4; m5insL = 12;

/* [Slit + snout] */
slitTilt = 10;
slitSlideW = 12; slitSlideH = 22; slitSlideT = 3.2;
snoutID = 30;  // entry bore snoutID-4 = 26 vs ~20 mm beam at the flange
scopeBoreD = 44; scopeFlangeD = 56;
scopeThreadD = 48; scopeThreadP = 0.75;  // M48x0.75 female (telescope side)
scopeThreadL = 9;
snoutExt = 50;       // external snout extension: moves the OTA's fat parts
                     // forward so the camera sits beside a Ø64 tube, not
                     // the Ø95 FSQ body. Beam at the far end ~30 mm.

/* [Camera port] */
camBoreD = 34; camTubeD = 56;
// prototype camera: ToupTek G3M678M — MEASURE and update (placeholder
// Ø40 x 70 body). Production IMX571: Ø80 body, Ø100x10 tilt flange, 108mm.
camFocD = 58; camFocL = 20;
camTiltD = 44; camTiltT = 4;
camBodyD = 40; camBodyL = 70;
camThreadD = 42; camThreadP = 0.75;  // M42x0.75 (T2) female, printed
camThreadL = 9; camThreadClr = 0.35; // radial print clearance

/* [Grating rotator] */
rotD = 56; pivotD = 8.05; tuneRange = 12;
armR = 70;           // M4x0.7 tangent at armR: 0.57 deg/turn
gratMax = 51; gratWinD = 40;

function u(a) = [cos(a), sin(a)];
eps = 0.01;
showBeams = true;    // draw the light path in part="preview"

// beam segment: frustum from p1 to p2 at beam height
module beam(p1, p2, d1, d2, col) {
    L = norm([p2[0] - p1[0], p2[1] - p1[1]]);
    a = atan2(p2[1] - p1[1], p2[0] - p1[0]);
    color(col, 0.45)
        translate([p1[0], p1[1], beamH]) rotate([0, 0, a]) rotate([0, 90, 0])
            cylinder(h = L, d1 = d1, d2 = d2, $fn = 48);
}

module light_path() {
    // telescope cone: front wall -> slit (converges to the slit)
    beam([minX - snoutExt, 0], slitP, 26, 0.8, "gold");
    // slit -> OAP1: diverging f/6.9 cone (+ field)
    beam(slitP, oap1P, 0.8, 16, "gold");
    // OAP1 -> grating: collimated, ~13 mm
    beam(oap1P, gratP, 13, 13, "orange");
    // grating -> OAP2: anamorphically widened (cos b / cos a ~ 1.6 at Ha)
    beam(gratP, oap2P, 19, 19, "red");
    // OAP2 -> sensor: converging to the spectrum image
    beam(oap2P, sensP, 19, 3, "crimson");
}

module deck_labels() {
    for (lp = [[slitP, "SLIT", 8], [oap1P, "OAP1", 10],
               [gratP, "GRATING", 10], [oap2P, "OAP2", 10],
               [sensP, "SENSOR", 8]])
        color("white") translate([lp[0][0], lp[0][1] - 14, 0.2])
            linear_extrude(0.8) text(lp[1], size = lp[2],
                                     halign = "center", font = "Liberation Sans:style=Bold");
}

// deck extents: optical features plus the mirror-slab corner points
slab1F = [oap1P[0] - mirrorStack * cos(c1Ang), oap1P[1] - mirrorStack * sin(c1Ang)];
slab2F = [oap2P[0] + mirrorStack * cos(c2Ang), oap2P[1] + mirrorStack * sin(c2Ang)];
function slabPts(f, a, w) = [for (s = [-1, 1], b = [0, 1])
    [f[0] + s * (w / 2) * cos(a + 90) - b * slabT * cos(a),
     f[1] + s * (w / 2) * sin(a + 90) - b * slabT * sin(a)]];
allPts = concat([slitP, gratP, sensP, [0, 0]],
                slabPts(slab1F, c1Ang, slab1W),
                slabPts(slab2F, c2Ang + 180, slab2W),
                [[gratP[0], gratP[1] - rotD - 20]]);
minX = min([for (p = allPts) p[0]]) - margin;
maxX = max([for (p = allPts) p[0]]) + 8;
minY = min([for (p = allPts) p[1]]) - 8;
maxY = max([for (p = allPts) p[1]]) + 8;
armAng = gratNormAng + 270;          // rotor arm at Ha tuning
armAngs = [for (a = gratNormAngs) a + 270];   // per-line detents
armLo = min(armAngs) - 3; armHi = max(armAngs) + 3;

// Male thread form, used directly or as a cutter for female threads.
// Twisted-lobe method: 240-deg lobe -> ~55-60 deg included flank angle.
module thread_male(d, pitch, len) {
    hth = 0.6495 * pitch;
    rmin = d / 2 - hth;
    pts = [for (a = [0:6:359])
        let (t = abs(((a + 180) % 360) - 180),
             f = min(0.92, max(0, 1 - t / 120)))
        [(rmin + f * hth) * cos(a), (rmin + f * hth) * sin(a)]];
    linear_extrude(len, twist = -360 * len / pitch,
                   slices = ceil(len / pitch) * 24, convexity = 10)
        polygon(pts);
    cylinder(h = len, d = 2 * rmin + 0.2, $fn = 96);
}

module mirror_slab(faceP, normAng, w, hole) {
    difference() {
        linear_extrude(wallH)
            translate(faceP) rotate([0, 0, normAng])
                translate([-slabT / 2, 0]) square([slabT, w], center = true);
        for (hv = [[hole, hole], [hole, -hole], [-hole, hole]])
            translate([faceP[0], faceP[1], beamH + hv[1]])
                rotate([0, 0, normAng]) rotate([0, 90, 0])
                    translate([0, hv[0], -m5insL])
                        cylinder(h = m5insL + eps, d = m5insD, $fn = 32);
    }
}

module along(p2, a) {  // place children at beamH, local +z along angle a
    translate([p2[0], p2[1], beamH]) rotate([0, 0, a]) rotate([0, 90, 0])
        children();
}

module body() {
    camLen = (sensP[0] - minX) / -u(dfAng)[0]; // sensor plane -> front wall
    veeX = gratP[0] + (25 - gratP[1]) / u(c2Ang)[1] * u(c2Ang)[0];
    difference() {
        union() {
            translate([minX, minY, -deckT])
                cube([maxX - minX, maxY - minY, deckT]);
            linear_extrude(wallH) difference() {
                translate([minX, minY]) square([maxX - minX, maxY - minY]);
                translate([minX + wallT, minY + wallT])
                    square([maxX - minX - 2 * wallT, maxY - minY - 2 * wallT]);
            }
            mirror_slab(slab1F, c1Ang, slab1W, km1Hole);
            mirror_slab(slab2F, c2Ang + 180, slab2W, km2Hole);
            // slit tower
            linear_extrude(beamH + slitSlideH)
                translate([-10, -17]) square([14, 34]);
            // snout: front wall -> slit tower (enclosed square tunnel)
            translate([minX, -snoutID / 2 - wallT, beamH - snoutID / 2 - wallT])
                cube([-minX - 8, snoutID + 2 * wallT, snoutID + 2 * wallT]);
            // telescope snout extension + flange (exterior)
            along([minX, 0], 180)
                cylinder(h = snoutExt, d = scopeFlangeD, $fn = 96);
            // camera tunnel: sensor plane -> through front wall + flange
            along(sensP, dfAng) cylinder(h = camLen + 10, d = camTubeD, $fn = 96);
            // grating turntable seat
            translate([gratP[0], gratP[1], 0])
                cylinder(h = 6, d = rotD + 10, $fn = 96);
            // tangent-screw posts: one per line detent (CaK / He / Ha)
            for (a = armAngs)
                translate([gratP[0] + (armR + 14) * u(a)[0],
                           gratP[1] + (armR + 14) * u(a)[1], 0])
                    cylinder(h = 22, d = 16, $fn = 48);
            // stray-light vane at by = +25: separates the slit/snout
            // region from the camera corridor. Ends at bx=68 — beyond
            // that the OAP1 mount slab is the separator, and the mirror
            // substrate envelope must stay clear.
            linear_extrude(wallH)
                translate([minX + wallT - eps, 25])
                    square([68 - minX - wallT + eps, 3]);
        }
        // slit cartridge pocket + optical opening (tilted about vertical)
        translate([0, 0, beamH]) rotate([0, 0, slitTilt]) {
            translate([0, 0, slitSlideH / 2])
                cube([slitSlideT, slitSlideW, 3 * slitSlideH], center = true);
            rotate([0, 90, 0])
                cylinder(h = 44, d = 9, center = true, $fn = 48);
        }
        // snout bore (stops at slit tower wall)
        translate([minX - 20, 0, beamH]) rotate([0, 90, 90]) rotate([0, 90, 0])
            cylinder(h = -minX + 20 - 6, d = snoutID - 4, $fn = 64);
        // telescope bore through extension + front wall, stepped behind
        // the M48x0.75 female thread at the far face
        along([minX + 16, 0], 180)
            cylinder(h = snoutExt + 40, d = scopeBoreD, $fn = 96);
        along([minX, 0], 180) translate([0, 0, snoutExt - scopeThreadL]) {
            thread_male(scopeThreadD + 2 * camThreadClr, scopeThreadP,
                        scopeThreadL + 1);
            translate([0, 0, scopeThreadL - 0.8])
                cylinder(h = 2, d1 = scopeThreadD - 1,
                         d2 = scopeThreadD + 1.6, $fn = 96);
        }
        // camera bore along df through tunnel, wall, flange
        along(sensP, dfAng)
            translate([0, 0, -6]) cylinder(h = camLen + 30 - camThreadL, d = camBoreD, $fn = 96);
        // M42x0.75 female thread at the exterior end (focuser interface):
        // cut with an oversized male form + entry chamfer
        along(sensP, dfAng) translate([0, 0, camLen + 10 - camThreadL]) {
            thread_male(camThreadD + 2 * camThreadClr, camThreadP,
                        camThreadL + 1);
            translate([0, 0, camThreadL - 0.8])
                cylinder(h = 2, d1 = camThreadD - 1, d2 = camThreadD + 1.6,
                         $fn = 96);
        }
        // grating pivot + clamp arc slot (centered on the arm direction)
        translate([gratP[0], gratP[1], -deckT - 1])
            cylinder(h = 40, d = pivotD, $fn = 48);
        translate([gratP[0], gratP[1], -deckT - 1])
            rotate([0, 0, armLo])
                rotate_extrude(angle = armHi - armLo, $fn = 256)
                    translate([armR - 12, 0]) square([4.3, 40]);
        // tangent screw: horizontal M4 insert through the post, aimed
        // tangentially (perpendicular to the arm) at the arm tip
        for (a = armAngs)
            translate([gratP[0] + (armR + 14) * u(a)[0],
                       gratP[1] + (armR + 14) * u(a)[1], 14])
                rotate([0, 0, a + 90]) rotate([0, 90, 0])
                    translate([0, 0, -20]) cylinder(h = 40, d = 3.4, $fn = 24);
        // vane aperture where the diffracted beam crosses by = 25
        translate([veeX, 25, beamH]) rotate([0, 0, c2Ang]) rotate([0, 90, 0])
            cylinder(h = 40, d = 32, center = true, $fn = 64);
    }
}

module rotor() {
    difference() {
        union() {
            cylinder(h = 8, d = rotD, $fn = 128);
            translate([-gratMax / 2 - 3, -3.5, 0])
                cube([gratMax + 6, 16, 8 + gratMax + 8]);
            rotate([0, 0, 180]) translate([0, -6, 0]) cube([armR, 12, 8]);
        }
        translate([0, 0, -1]) cylinder(h = 80, d = pivotD, $fn = 48);
        // grating slot, slide-in from top; front face registers on the
        // pivot-axis plane (y=0 local)
        translate([-gratMax / 2, 0, 8]) cube([gratMax, 10.2, gratMax + 9]);
        translate([0, -5, 8 + 4 + gratMax / 2]) rotate([90, 0, 0])
            cylinder(h = 20, d = gratWinD, center = true, $fn = 96);
        // rear nylon-tip clamp screw
        translate([0, 8, 8 + 4 + gratMax / 2]) rotate([-90, 0, 0])
            cylinder(h = 20, d = 4.4, $fn = 24);
        // clamp thumbscrew through the arm at armR-10 (into deck arc slot)
        rotate([0, 0, 180]) translate([armR - 10, 0, -1])
            cylinder(h = 12, d = 4.4, $fn = 24);
    }
}

module shelyak_adapter() {
    difference() {
        cube([gratMax - 0.4, 9.8, gratMax - 0.4]);
        translate([(gratMax - 25.6) / 2, -1, (gratMax - 25.6) / 2])
            cube([25.6, 7.2, 25.6]);
        translate([(gratMax - 0.4) / 2, 12, (gratMax - 0.4) / 2])
            rotate([90, 0, 0]) cylinder(h = 20, d = 22, $fn = 64);
    }
}

// ghost camera envelope (reference only, renders transparent)
module camera_ghost() {
    camLenG = (sensP[0] - minX) / -u(dfAng)[0];
    %along(sensP, dfAng) translate([0, 0, camLenG + 10]) {
        cylinder(h = camFocL, d = camFocD, $fn = 64);
        translate([0, 0, camFocL]) cylinder(h = camTiltT, d = camTiltD, $fn = 64);
        translate([0, 0, camFocL + camTiltT])
            cylinder(h = camBodyL, d = camBodyD, $fn = 64);
    }
}

if (part == "body" || part == "preview") body();
if (part == "preview") {
    camera_ghost();
    deck_labels();
    if (showBeams) light_path();
}
if (part == "rotor") rotor();
if (part == "preview")
    translate([gratP[0], gratP[1], 6.2]) rotate([0, 0, armAng - 180]) rotor();
if (part == "shelyak_adapter") shelyak_adapter();
